### ISSUE TITLE
CONTRIBUTING.md: broken link to "examples folder"

### ISSUE THREAD

**Issue by nikitakoselev** [blst-security/cherrybomb#104]
**Describe the bug**
CONTRIBUTING.md, "We have already implemented a OAS interface that can read and destructure the inputted file (a few OAS files for example are available in the [examples folder](https://github.com/blst-security/cherrybomb/swagger/examples))." - refers to a wrong folder

**To Reproduce**
1. Go to CONTRIBUTING.md
2. Click on 'examples folder' URL
3. See error 404

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/6383738/213896069-1f3ec048-55ea-4dbf-8d4b-ae3e9437130d.png)
![image](https://user-images.githubusercontent.com/6383738/213896079-03dcbfa7-6953-4200-b8e6-7cb24efea6ae.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Chrome
 - Version 109.0.5414.75

**Additional context**
# The correct link might be the https://github.com/blst-security/cherrybomb/tree/main/swagger/examples
# Might be a "good first time issue"

**Comment by OmerWow** [comment]
Fixed in https://github.com/blst-security/cherrybomb/pull/105
