### ISSUE TITLE
YAML support broken?

### ISSUE THREAD

**Issue by rngtng** [blst-security/cherrybomb#111]
**Describe the bug**
According to https://github.com/blst-security/cherrybomb/issues/19 yaml support should be there, but I couldn't get it working:

An OAS 3.1 file in yaml format raises error:

```
> cherrybomb --file foo.yaml
 v1.0.0
Starting Cherrybomb...
Opening OAS file...
Parsing OAS file...
Error: Error parsing OAS file: expected value at line 1 column
```

Same content as json works fine.

**To Reproduce**
1. `wget https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/examples/v3.1/non-oauth-scopes.yaml`
2. `cherrybomb --file non-oauth-scopes.yaml`
3. FAILURE!

But JSON works:
1. `wget https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/examples/v3.1/non-oauth-scopes.json`
2. `cherrybomb --file non-oauth-scopes.json`
3. SUCCESS!

**Expected behavior**
YAML File gets successfully parsed

**Version**
 - Version 1.0.0

**Comment by DeliciousBounty** [comment]
Hey @rngtng, 
Thank you for taking the time to contact us.
You are correct, We used to support the YAML OpenAPI file in previous versions.
However, for the time being, we only support JSON files in this new release.
Thank you  to pay attention to us!
It's already on our list of things to do.
I will notify you once this feature is available.

**Comment by rngtng** [comment]
Cool, thanks the fast feedback. No worries, there are enough yaml -> json converters out there…

**Comment by jayvdb** [comment]
This is fixed..?

**Comment by DeliciousBounty** [comment]
Thank @jayvdb Yes it is fixed, and we also updated the crates.
I close this issue
