### ISSUE TITLE
Publish crate as a library

### ISSUE THREAD

**Issue by Kinrany** [blst-security/cherrybomb#126]
**Is your feature request related to a problem? Please describe.**
I'd like to apply the tool in CI to an API written in Rust.

**Describe the solution you'd like**
Publish the crate as a library on crates.io. This will allow using the library in tests in-process, without having to compile or install it separately and without having to expose an internal schema.

**Comment by GuyL99** [comment]
Hi @Kinrany Cherrybomb is already published as a crate in crates.io.
Here is the link: [https://crates.io/crates/cherrybomb](https://crates.io/crates/cherrybomb)

**Comment by Kinrany** [comment]
The request was for publishing as a library.

**Comment by GuyL99** [comment]
I'm sorry, I misunderstood.
Which part of cherrybomb did you want posted as a library?

**Comment by Kinrany** [comment]
Hopefully everything that can be done with the CLI! Even just the top-level Clap type would be nice, assuming that's what you use.

**Comment by jayvdb** [comment]
This would be fantastic. For me it would allow me to workaround https://github.com/blst-security/cherrybomb/pull/117 , and force running of cherrybomb within the tools I used to generate or read the openapi, such as https://github.com/oxidecomputer/progenitor , so I can first have cherrybomb sanity check the input before handing it to other libraries which are going to fail badly if the input is broken.

**Comment by jayvdb** [comment]
Looks like most of this app is published as https://crates.io/crates/cherrybomb-engine
