### ISSUE TITLE
api key is not able to generate 

### ISSUE THREAD

**Issue by kpreety** [blst-security/cherrybomb#135]
**Describe the bug**
I am trying to generate api key from https://cicd.blstsecurity.com/ ,but its keep loading .

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by DeliciousBounty** [comment]
Hey @kpreety !
We appreciate you contacting us about this. We just fixed it; please get in touch with us if you run across any new issues.

nathan.s@blstsecurity.com
