### ISSUE TITLE
include/exclude Seem to Have no Effect

### ISSUE THREAD

**Issue by afrazkhan** [blst-security/cherrybomb#140]
## Describe the bug

Adding the include/exclude rules in the configuration seem to have no effect.

## To Reproduce

1. Add something like the following into a configuration file:

        ```
        {
            "profile": "Passive",
            "passive_exclude": [
                "DESCRIPTION"
            ],
            "active_exclude": [
                "DESCRIPTION"
            ]
        }
        ```

1. Run with `cherrybomb -c [CONFIG_FILE] -f [FILE_TO_CHECK]`

I've also tried with every variation in the exclude strings I could think of, like:

- `DESCRIPTION path:/my-path operation:GET`
- `DESCRIPTION swagger path:/my-path operation:GET`
- `swagger path:/my-path operation:GET DESCRIPTION`
- `DESCRIPTION:swagger:path:/my-path operation:GET`
- `DESCRIPTION, swagger:path:/my-path, operation:GET`

And many more! ;)

## Expected behavior

The excluded checks are excluded.

# Screenshots

# Desktop (please complete the following information):

**Comment by DeliciousBounty** [comment]
Hey @afrazkhan, Thanks for catching that. But we still do not publicly update the crate. You can try to compile locally, and that should be solved.
We will update when the new crates are available.

**Comment by afrazkhan** [comment]
Thanks @DeliciousBounty. Do you know if the Docker image you provide has the latest code already? Else I'll build one for my CI myself.

**Comment by DeliciousBounty** [comment]
@afrazkhan You need to build it by yourself

**Comment by DeliciousBounty** [comment]
We already updated the crate, so I will close this issue.If it rises again, I invite you to open a new one.
