### ISSUE TITLE
cherrybomb is not working 

### ISSUE THREAD

**Issue by anirudh-hegde** [blst-security/cherrybomb#145]
when i installed cherrybomb : 

curl https://cherrybomb.blstsecurity.com/install | /bin/bash
                                                         
 % Total    % Received % Xferd  Average Speed   Time    Time     Time  CurrentDload  Upload   Total   Spent    Left  Speed
     100  1518  100  1518    0     0    663      0  0:00:02  0:00:02 --:--:--   663
\033[32;1m DETECTED OS - linux_gnu\033[0m
\033[34;1m DOWNLOADING CHERRYBOMB\033[0m
\033[32;1m DONE DOWNLOADING\033[0m
\033[34;1m INSTALLING\033[0m
MOVING CHERRYBOMB BIN INTO /usr/local/bin/, MAY REQUIRE sudo
\033[32;1m DONE INSTALLING RUN cherrybomb to test\033[0m

cherrybomb --version

cherrybomb: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory

OS: Ubuntu 22.04 Jammy

**Comment by GuyL99** [comment]
Thanks for raising the issue, you need to install openssl before you run cherrybomb, run:
`sudo apt-get install libssl-dev`
And it should work. I would also suggest that you build cherrybomb from source, because for now it's the most updated version

**Comment by anirudh-hegde** [comment]
Thank you @GuyL99.
