### ISSUE TITLE
Cherrybomb error - Invalid peer certificate: Expired

### ISSUE THREAD

**Issue by abnair24** [blst-security/cherrybomb#147]
**Describe the bug**

on executing cherrybomb cli, below error is observed

━━━┳╮╱╱╱╱╱╱╱╱╱╱╱╱╭╮╱╱╱╱╱╱╱╭╮
┃╭━╮┃┃╱╱╱╱╱╱╱╱╱╱╱╱┃┃╱╱╱╱╱╱╱┃┃
┃┃╱╰┫╰━┳━━┳━┳━┳╮╱╭┫╰━┳━━┳╮╭┫╰━╮
┃┃╱╭┫╭╮┃┃━┫╭┫╭┫┃╱┃┃╭╮┃╭╮┃╰╯┃╭╮┃
┃╰━╯┃┃┃┃┃━┫┃┃┃┃╰━╯┃╰╯┃╰╯┃┃┃┃╰╯┃
╰━━━┻╯╰┻━━┻╯╰╯╰━╮╭┻━━┻━━┻┻┻┻━━╯
╱╱╱╱╱╱╱╱╱╱╱╱╱╱╭━╯┃
╱╱╱╱╱╱╱╱╱╱╱╱╱╱╰━━╯       v1.0.1

Error: error sending request for url (https://cherrybomb.blstsecurity.com/tel): error trying to connect: invalid peer certificate: Expired

Caused by:
    0: error trying to connect: invalid peer certificate: Expired
    1: invalid peer certificate: Expired

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: mac
 - Version 1.o.1

**Additional context**

**Comment by andyaspellclark-moj** [comment]
I am getting the same error:

```
 cherrybomb --file ./api-docs.json --profile passive

╭━━━┳╮╱╱╱╱╱╱╱╱╱╱╱╱╭╮╱╱╱╱╱╱╱╭╮
┃╭━╮┃┃╱╱╱╱╱╱╱╱╱╱╱╱┃┃╱╱╱╱╱╱╱┃┃
┃┃╱╰┫╰━┳━━┳━┳━┳╮╱╭┫╰━┳━━┳╮╭┫╰━╮
┃┃╱╭┫╭╮┃┃━┫╭┫╭┫┃╱┃┃╭╮┃╭╮┃╰╯┃╭╮┃
┃╰━╯┃┃┃┃┃━┫┃┃┃┃╰━╯┃╰╯┃╰╯┃┃┃┃╰╯┃
╰━━━┻╯╰┻━━┻╯╰╯╰━╮╭┻━━┻━━┻┻┻┻━━╯
╱╱╱╱╱╱╱╱╱╱╱╱╱╱╭━╯┃
╱╱╱╱╱╱╱╱╱╱╱╱╱╱╰━━╯       v1.0.0

Error: error sending request for url (https://cherrybomb.blstsecurity.com/tel): error trying to connect: The certificate was not trusted.

Caused by:
    0: error trying to connect: The certificate was not trusted.
    1: The certificate was not trusted.
```

**Comment by DeliciousBounty** [comment]
Hello @andyaspellclark-moj @abnair24 , and for thank for raising this issue. We are @GuyL99 working on it, for the moment please disable telemetry by sending the argument  --no-telemetry with cherrybomb

**Comment by andyaspellclark-moj** [comment]
thats fixed that issue, thanks

**Comment by andyaspellclark-moj** [comment]
adding --no-telemetry now allows cherrybomb to run on my local machine, but trying to install and run it in our pipeline is failing with invalid certificate now.

**Comment by DeliciousBounty** [comment]
I close this issue we fixed the certificate.
