### ISSUE TITLE
💡 Provide CherryBomb in an official Docker image

### ISSUE THREAD

**Issue by AErmie** [blst-security/cherrybomb#16]
**Is your feature request related to a problem? Please describe.**
For users that want to run/use your tool in a CI/CD pipeline as part of a quality check, needing to install the tool locally may not always be an option.

**Describe the solution you'd like**
I would like to see this tool be made available in an official Docker image like many other CLI-based tools provide (ie. [AquaSec/Trivy](https://hub.docker.com/r/aquasec/trivy), [BridgeCrew/Checkov](https://hub.docker.com/r/bridgecrew/checkov), etc.).

**Describe alternatives you've considered**
A self-built container with the tool installed.

**Additional context**
None

**Comment by GuyL99** [comment]
I'll add it to the roadmap, we'll probably be able to get it stabilised in about two weeks, I'll update this issue once there is an rc of a container image

**Comment by prakharporwal** [comment]
Can I try this out ?

**Comment by BartvdBerkHU** [comment]
Hi, I want to make my first open source contribution by integrating this tool into another project in the form of a Kubernetes job, for this I need a container image. I could create this on my own, but saw this issue and don't want to perform duplicate work.

@prakharporwal Do you have an update on this issue already or maybe you have a working Dockerfile I could use for development?

**Comment by GuyL99** [comment]
@prakharporwal if you need some help in order to finish it I'll add in @RazMag or @DeliciousBounty to help you.
@BartvdBerkHU I appreciate the will to contribute, what OS project do you intend to integrate Cherrybomb to?

**Comment by prakharporwal** [comment]
@GuyL99  I have made a update on the PR can you check I am facing a issue.
@BartvdBerkHU I have a Dockerfile created but it has a small issue . I am discussing and looking into it.

**Comment by RazMag** [comment]
Cherrybomb is now available in an official docker container. see [the readme ](https://github.com/blst-security/cherrybomb/blob/main/README.md) for info on how to use it. Thank you for your help :)
