### ISSUE TITLE
Remove or sort unused code into new `issue`s

### ISSUE THREAD

**Issue by eureka-cpu** [blst-security/cherrybomb#42]
There's a fairly substantial amount of logical code that's stored as comments in this repo. There seems to be a mixture of code that may get used later, and code that either is no longer going to be used or has been corrected but the predecessor was left as a comment instead of being removed. I'll compile a list to make tracking this easier.

In general it may be better practice to store unused code on a local branch if the intention is to use it at a later date, otherwise it may end up forgotten and create clutter as the code base grows. Another option would be to create an issue describing the problem and include the code as a possible solution so that others can understand what the intent of that code is. 

Attacker:
- [x] #98
- [ ] `attacker::auth`
Cli:
- [ ] `cli::actions`
- [ ] `cli::auth`
- [ ] `cli::main`
- [ ] `cli::main_old`
Decider:
- [ ] `decider::lib`
- [ ] `decider::rule_based`
Mapper:
- [ ] `mapper::digest::ep`
- [ ] `mapper::digest::hash`
- [ ] `mapper::digest::utils`
- [ ] `mapper::path::hash`
- [ ] `mapper::path::mod`
- [ ] `mapper::lib`
Swagger:
- [ ] `swagger::scan::active::http_client::auth`
- [ ] `swagger::scan::active::additional_checks`
- [ ] `swagger::scan::active::logs`
- [ ] `swagger::scan::active::mod`
- [ ] `swagger::scan::passive::general`
- [ ] `swagger::scan::passive::mod`
- [ ] `swagger::scan::passive::utils`
- [ ] `swagger::scan::checks`
- [ ] `swagger::scan::mod`
- [ ] `swagger::scan::print`
- [ ] `swagger::tables::param_table`
- [ ] `swagger::ep`
- [ ] `swagger::lib`
- [ ] `swagger::main`
- [ ] `swagger::param`
- [ ] `swagger::schema`

**Comment by GuyL99** [comment]
We're planning to split everything up and leave only the necessary parts when we release Cherrybomb 0.7, I'll leave it open for now so we can be sure to do that.

**Comment by DeliciousBounty** [comment]
Hello @eureka-cpu 
We are working on the next release where we are removing unused code and comments.
