### ISSUE TITLE
The CONTRIBUTING.md file specifies a branch called "canary" to pull requests from - this seems absent. What branch does one use instead?

### ISSUE THREAD

**Issue by agatekartik** [blst-security/cherrybomb#51]
**Describe the bug**
Missing branch "canary" mentioned in CONTRIBUTING.md - kindly specify the correct branch to use for contributions

**To Reproduce**
1. Go to CONTRIBUTING.md
2. Scroll down to the section for developers
4. See branch "canary" mentioned there. There seems to be no such branch

**Expected behavior**
Please specify the correct branch for contributions

**Screenshots**
Pasting from the file:

> The development branch is canary. This is the branch that all pull requests should be made against.

**Comment by RazMag** [comment]
Hey @agatekartik, thank you for bringing this to our attention. I've updated the the CONTRIBUTING.md file with the relevant branch now (`dev`) and information about developing one of the new active check. :)
