### ISSUE TITLE
Build error `E0277`: trait bound `f64: std::cmp::Eq` is not satisfied

### ISSUE THREAD

**Issue by voxpelli** [blst-security/cherrybomb#65]
**Describe the bug**

**To Reproduce**
1. Checkout latest `main`
2. Run `cargo build --release`
3. See error

**Expected behavior**
The project would actually build.

**Screenshots**
<img width="864" alt="Skärmavbild 2022-08-23 kl  18 01 35" src="https://user-images.githubusercontent.com/34457/186206866-6f7603d4-fc0f-4d65-8b71-bd08ac2bff91.png">

> error[E0277]: the trait bound `f64: std::cmp::Eq` is not satisfied
>   --> swagger/src/schema.rs:56:5

https://github.com/blst-security/cherrybomb/blob/100453111366a8723162a649fd8954268e51731c/swagger/src/schema.rs#L56

>   = note: required because of the requirements on the impl of `std::cmp::Eq` for `std::option::Option<f64>`
> note: required by a bound in `AssertParamIsEq`
>   --> /Users/pelle/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/cmp.rs:317:31

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS 12.5.1 M1

**Additional context**
I guess this might be because I'm compiling on an M1 and thus is targeting `aarch64`?

**Comment by GuyL99** [comment]
Hi, what toolchain are you using? 
It can only compile on nightly, and I'll add it to the readme

**Comment by voxpelli** [comment]
@GuyL99 Rust 1.63.0, sorry for forgetting that very crucial information 😝

**Comment by voxpelli** [comment]
Could you add a [`rust-toolchain.toml`](https://rust-lang.github.io/rustup/overrides.html?#the-toolchain-file) file?

**Comment by GuyL99** [comment]
@RazMag and @DeliciousBounty, can you do it?

**Comment by RazMag** [comment]
Thanks @voxpelli should be fixed now

**Comment by dmdhrumilmistry** [comment]
I'm getting same error when I ran 

```bash
# rust version
$ rustc --version
rustc 1.65.0 (897e37553 2022-11-02)

# installing cherrybomb
$ cargo install cherrybomb
```

Screenshot:
![image](https://user-images.githubusercontent.com/56185972/201470983-658f5ef2-609f-462e-8690-d6d5b8a867f9.png)

How can I fix the issue?

**Comment by DeliciousBounty** [comment]
@dmdhrumilmistry Do you compile on  rust nightly?

**Comment by dmdhrumilmistry** [comment]
> @dmdhrumilmistry Do you compile on rust nightly?

I believe I'm using a stable release since I installed rust using default options.

**Comment by RazMag** [comment]
Thank you @dmdhrumilmistry looking into this rn

**Comment by RazMag** [comment]
Hey this should be fixed now in dev, in crates.io and soon in the main branch.
