### ISSUE TITLE
Failure while trying to install cherrybomb

### ISSUE THREAD

**Issue by Arthurdw** [blst-security/cherrybomb#80]
**Describe the bug**
The application won't compile through cargo compile.

**To Reproduce**
1. Execute the `cargo install cherrybomb` command

**Expected behavior**
A proper installation/compile

**Screenshots**
![image](https://user-images.githubusercontent.com/38541241/194525531-551aff50-97a7-47ae-bc7b-7f0ca9590ca9.png)

**Desktop (please complete the following information):**
 - OS: `Linux compooter 5.15.65-1-MANJARO #1 SMP PREEMPT Mon Sep 5 10:15:47 UTC 2022 x86_64 GNU/Linux`

**Comment by DeliciousBounty** [comment]
Hello,
Try to run Rust nightly by this command, it should work :)
`$ rustup install nightly
`
