### ISSUE TITLE
Authorization input validation - Error handling

### ISSUE THREAD

**Issue by RoyB99** [blst-security/cherrybomb#86]
Add better error handling in the auth.rs (/swagger/src/scan/active/http_client) file for auth types.
line 15 includes a panic and the rest trust the input to be valid.

There needs to be error handling for input validation. 

Cheers,

**Comment by DeliciousBounty** [comment]
@RoyB99 
I appreciate your suggestion. We'll include support for more sophisticated error handling in the upcoming release.
