### ISSUE TITLE
To release Cherrybomb binaries for common archs

### ISSUE THREAD

**Issue by dmdhrumilmistry** [blst-security/cherrybomb#88]
**Is your feature request related to a problem? Please describe.**
Can blst-security team release cherrybomb binaries during the official release? It'll help users download binaries directly from GitHub.

**Describe the solution you'd like**
I'll like to download binaries from the GitHub release section and use cherrybomb on the go.

**Comment by DeliciousBounty** [comment]
Hey @dmdhrumilmistry  !

We're thinking of adding binaries for the next release.
Thanks for the  suggestion!
