### ISSUE TITLE
{type: number, format: int32} should be a validation error

### ISSUE THREAD

**Issue by jayvdb** [blst-security/cherrybomb#96]
**Is your feature request related to a problem? Please describe.**
`{type: number, format: int32}` is not ideal [OAS 3.0.3](https://swagger.io/specification/), as it defines a format which should be an `integer`, but uses `type: number` when the `type: integer` should be used.

As it is ambiguous, the validator should emit an error of some sort, as openapi tools are very likely to either ignore either `type` or `format`, or fail when trying to combined the two.

An example of a tool which silently ignores the `format` is https://github.com/oxidecomputer/progenitor/issues/266

**Describe the solution you'd like**
Detect `type: number` and a integer `format`, and `type: integer` and a float `format`.

https://github.com/zalando/zally (Kotlin) does detect this as rule [`MUST define a format for number and integer types`](https://opensource.zalando.com/restful-api-guidelines/#171)

**Describe alternatives you've considered**

**Additional context**

**Comment by OmerWow** [comment]
Hey @jayvdb

Thanks for the feature suggestion!

We're thinking about adding a new passive check that will check for integrity of types, is that what you had in mind?

**Comment by jayvdb** [comment]
Yes

**Comment by OmerWow** [comment]
Great then!

We're adding this to our future development plans, thanks for the suggestion :)

**Comment by OmerWow** [comment]
Hey @jayvdb 

Just wanted to let you know we're adding the new passive check to Cherrybomb, this is the link to the PR: https://github.com/blst-security/cherrybomb/pull/97

Thanks again for the suggestion :)

**Comment by DeliciousBounty** [comment]
Hii @jayvdb 
Just wanted to let you know that there is a new passive check that responds to your feature suggestion: 
 https://github.com/blst-security/cherrybomb/blob/b2eb8b421cd4a78a107fe41f3921275a516986be/cherrybomb-engine/src/scan/passive/additions_checks.rs#L39
I close this issue
